logging:
  config: classpath:logback.xml
server:
  port: 8088
xxl:
  job:
    ### xxl-job, access token
    ### 执行器核调度中心之间的安全协议配置，可不配
    accessToken: ''

    admin:
      #admin 模块要和执行器进行通信，配置admin [调度中心的地址]
      addresses: http://127.0.0.1:9876/xxl-job-admin
    executor:
      address: ''
      ### xxl-job executor appname 执行器的名称，用来给执行器分组
      appname: xxl-job-executor-sample
      ### xxl-job executor server-info，可以不配，当执行器的服务器有虚拟网卡或双网卡时配置
      ip: ''
      ###执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；xxl-job executor log-path,日志存储目录
      logpath: D:\code\xxl-job-logDir
      ###执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9992
